djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from personal.views import (
    contact,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('personal.urls')),
    path('items/', include('item.urls')),
    path('kontakt/', contact, name='contact'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
]

personal/urls.py
from django.urls import path

from . import views

app_name = 'personal'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('kategorie/<int:pk>/', views.categoryIndex, name='categoryIndex')
]

item/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Kategorie(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Kategorien'

    def __str__(self):
        return self.name


class Produkt(models.Model):
    category = models.ForeignKey(Kategorie, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_used = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

personal/models.py
from django.db import models


# Create your models here.

item/views.py
from django.shortcuts import render, get_object_or_404
from .models import Produkt


# Create your views here.
def detail(request, pk):
    item = get_object_or_404(Produkt, pk=pk)
    related_items = Produkt.objects.filter(category=item.category).exclude(pk=pk)[0:3]
    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })

personal/views.py
from django.shortcuts import render, get_object_or_404

from item.models import Kategorie, Produkt


# Create your views here.

def index(request):
    items = Produkt.objects.all()[0:6]
    categories = Kategorie.objects.all()
    return render(request, "personal/index.html", {
        'categories': categories,
        'items': items,
    })


def categoryIndex(request, pk):
    categories = Kategorie.objects.all()
    category = get_object_or_404(Kategorie, pk=pk)
    related_items_to_category = Produkt.objects.filter(category=category).exclude(pk=pk)
    return render(request, "personal/categoryIndex.html", {
        'category': category,
        'related_items_to_category': related_items_to_category,
        'categories': categories,
    })


def contact(request):
    return render(request, "personal/contact.html")

item/templates/item/detail.html
{% extends 'personal/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.image.url }}" class="rounded-xl" height="200" width="300">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        <p class="text-gray-500"><strong>Preis: {{ item.price }}</strong></p>
        {% if item.is_used %}
            <p class="text-gray-500"><strong>Zustand: Gebraucht</strong></p>
            <p class="text-gray-500"><strong>Garantie: 6 Monate</strong></p>
        {% endif %}
        {% if not item.is_used %}
            <p class="text-gray-500"><strong>Zustand: Neu</strong></p>
            <p class="text-gray-500"><strong>Garantie: 12 Monate</strong></p>
        {% endif %}
        <br>
        {% if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Beschreibung:</strong><br>
                {{ item.description }}
            </p>
        {% endif %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Ähnliche Produkte</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in related_items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl" width="500">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Preis: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
</div>
{% endblock %}

personal/templates/personal/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <meta charset="UTF-8">
        <!--content with width and initial-scale makes the site look good on all  devices-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0f">
        <script src="https://cdn.tailwindcss.com"></script>
        <title>{% block title %}{% endblock %} | Elektrogeräte Leo</title>
        <style>
            .header {
                background-color: red;
                padding-left: 1.5rem;
                padding-right: 1.5rem;
                padding-top: 1.5rem;
                padding-bottom: 1.5rem;
                justify-content: space-between;
                align-items: center;
                border-bottom-width: 1px;
                border-color: rgb(229 231 235);
                display: flex;
            }
            .footer {
                padding-left: 1.5rem;
                padding-right: 1.5rem;
                padding-top: 1.5rem;
                padding-bottom: 1.5rem;
                justify-content: space-between;
                background-color: #1F2937;
                display: flex;
            }

            .product-content{
            margin-top: 1.5rem;
            padding-left: 1.5rem;
            padding-right: 1.5rem;
            padding-top: 3rem;
            padding-bottom: 3rem;
            background-color: #f5f5f5;
            border-radius: 1.5rem;
        }
        .product-order{
            display: grid;
            grid-template-columns: auto auto auto;
            gap: 3rem;
        }
        @media (max-width: 767px) {
                .hidden-mobile {
                    display: none;
                }
                .product-order{
                    display: grid;
                    grid-template-columns: auto;
                    gap: 3rem;
                }
            }
        </style>
    </head>
    <body>

        <nav class="header"  >
            <a href="/">
            <img src="/media/Screen Shot 2023-04-08 at 8.50.06 PM.png" width="200" height="200">

            </a>
            <div class="text-center">
                 <a class="text-5xl " style="color:yellow ;font-stretch: expanded">LEO - Möbel</a>
                <br>
                <a class="text-2xl " style="color:white">AN- UND VERKAUF</a>
                <br>
                <a class="text-2xl " style="color:white">VON GEBRAUCHTEN</a>
                <br>
                <a class="text-2xl " style="color:white">E-GERÄTEN UND MÖBELN</a>
            </div>
            <form action="/search" method="get" class="hidden-mobile">
                <label for="search" style="color: white;">Suche:</label>
                <input type="text" id="search" name="q">
            <button type="submit" style="color: white; background-color: transparent; border: none;"><i class="fa fa-search" style="color: white;"></i></button>
            </form>
        </nav>

        <!-- we use class to set the size and grid -->
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="footer">
            <div class="w-2/>3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">Informationen</h3>

                <p class="text-lg text-gray-500">Hier kommen Informationen über das Unternehmen hin. Bla Bla</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menü</h3>

                <ul class="space-y-2">
                    <li><a href="{% url 'personal:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Kontakt</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Impressum</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Rechtliches</a></li>
                </ul>

            </div>
        </footer>

    </body>
</html>

personal/templates/personal/categoryIndex.html
{% extends 'personal/base.html' %}

{% block title %}{{ category.name }}{% endblock %}


{% block content %}
<div class="product-content">
        <h2 class="mb-12 text-2xl text-center">Produkte für {{ category.name }}</h2>

        <div class="product-order">
            {% for item in related_items_to_category %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Preis: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Kategorien</h2>

        <div class="product-order">
            {% for category in categories %}
                <div>
                    <a href="{% url 'personal:categoryIndex' category.id %}">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ item.items.count }} Produkte</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock  %}

personal/templates/personal/contact.html
{% extends 'personal/base.html' %}

{% block title %}Kontakt{% endblock %}


{% block content %}
<h1>Die Kontakt Seite</h1>
{% endblock  %}

personal/templates/personal/index.html
{% extends 'personal/base.html' %}

{% block title %}Willkommen{% endblock %}


{% block content %}
    <div class="product-content">
        <h2 class="mb-12 text-2xl text-center">Neue Produkte</h2>

        <div class="product-order">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl" width="300">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Preis: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Kategorien</h2>

        <div class="product-order">
            {% for category in categories %}
                <div>
                    <a href="{% url 'personal:categoryIndex' category.id %}">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count}} Produkte</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock  %}